esphome:
  name: night-light-bear

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

logger:

light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO2  # D4
    num_leds: 3
    name: "Night Light"
    id: led_light
    method: esp8266_uart  # Using UART instead of DMA