esphome:
  name: night-light-bear

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

logger:

web_server:
  port: 80
  version: 3

light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO2 # D4
    num_leds: 3
    name: "Night Light"
    id: led_light
    method: esp8266_uart # Using UART instead of DMA
    gamma_correct: 0.8
    default_transition_length: 3000ms
    restore_mode: ALWAYS_OFF
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
    on_turn_on:
      then:
        - light.turn_on:
            id: led_light
            transition_length: 3000ms
    on_turn_off:
      then:
        - light.turn_off:
            id: led_light
            transition_length: 3000ms